@backend_HostAddress = http://localhost:5186

POST {{backend_HostAddress}}/gameinfo/
Content-Type: application/json

{
  "PlayerId": 1,
  "OpponentId": 2,
  "GameState" : "none"
}

###


GET {{backend_HostAddress}}/gameinfo

###

@id=8
GET {{backend_HostAddress}}/gameinfo/{{id}}

###

PUT {{backend_HostAddress}}/gameInfo/{{id}}
Content-Type: application/json

{
  "PlayerId" : 5,
  "OpponentId": 1,
  "GameState" : "two"
}

###


DELETE {{backend_HostAddress}}/gameinfo/{{id}}

###
DELETE {{backend_HostAddress}}/gameinfo/

###
