@backend_HostAddress = http://localhost:5186

POST {{backend_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}

###

GET {{backend_HostAddress}}/todoitems

###

@id=1
GET {{backend_HostAddress}}/todoitems/{{id}}

###

PUT {{backend_HostAddress}}/todoitems/{{id}}
Content-Type: application/json

{
  "id": 1,
  "name": "feed fish",
  "isComplete": false
}

###


DELETE {{backend_HostAddress}}/todoitems/{{id}}

###
